# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: DeployToVM
  displayName: "Deploy a VM"
  jobs:
  - deployment: InstallApacheAndConfigure
    displayName: "Instalar Apache y configurar página"
    environment:
      name: "admin-vm-s2-devops"      
      resourceType: VirtualMachine     
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Iniciando la instalación de Apache"
              sudo apt-get update
              sudo apt-get install -y apache2
              echo "Hola, configurado desde el pipeline la VM" | sudo tee /var/www/html/index.html
              sudo systemctl restart apache2
              echo "Instalación completa"
            displayName: "Instalar Apache y configurar index.html"
              
